macro(assert_strequal _varname _string)
	if(NOT DEFINED ${_varname})
		message(FATAL_ERROR "assert_strequal failed, variable ${_varname} is undefined")
	endif()

	if(NOT "${${_varname}}" STREQUAL "${_string}")
		message(FATAL_ERROR "assert_strequal failed: '${_varname}' != \"${_string}\"")
	endif()
endmacro()

macro(assert_undefined _varname)
	if(DEFINED ${_varname})
		message(FATAL_ERROR "assert_undefined failed: '${_varname}' is defined, value: ${${_varname}}")
	endif()
endmacro()

macro(assert_empty_or_undefined _varname)
	if(DEFINED ${_varname} AND NOT "${${_varname}}" STREQUAL "")
		message(FATAL_ERROR "assert_empty_or_undefined failed: '${_varname}' is \"${${_varname}}\"")
	endif()
endmacro()

# assert_listequal(listvar item1 item2 ...)
function(assert_listequal listvar)
	set(list1 ${${listvar}})
	set(list2 ${ARGN})
	list(LENGTH list1 l1)
	list(LENGTH list2 l2)
	if(l1 EQUAL l2)
		set(differs 0)
		math(EXPR l_minus_one "${l1}-1")
		foreach(i RANGE ${l_minus_one})
			list(GET list1 ${i} e1)
			list(GET list2 ${i} e2)
			if(NOT "${e1}" STREQUAL "${e2}")
				set(differs 1)
				break()
			endif()
		endforeach()
		if(NOT differs)
			return()
		endif()
	endif()
	acme_print_var(list1)
	acme_print_var(list2)
	message(FATAL_ERROR "assert_listequal failed, lists differ.")
endfunction()

message(STATUS "Testlib included")